### ISSUE TITLE
Rename `Id` type in `src/id.rs`

### ISSUE THREAD

**Issue by nicoburns** [linebender/xilem#168]
`Id` is kind of an awful name for this type, although this PR isn't really the place to fix it

_Originally posted by @DJMcNab in https://github.com/linebender/xilem/pull/166#discussion_r1480277627_

**Comment by DJMcNab** [comment]
To clarify, because the original comment wasn't constructive:

The type name tells you nothing about what the type is for (and the documentation also doesn't help). I also don't think this type is the identifier for "everything", i.e. both views and widgets, which might have justified this current name.

(Although I've not dug into the code to investigate this)

**Comment by DJMcNab** [comment]
The mentioned file is now gone, since #290

The ids are now `ViewId` in Xilem and `WidgetId` in Masonry.
