### ISSUE TITLE
Scrolling is inverted

### ISSUE THREAD

**Issue by nicoburns** [linebender/xilem#183]
Scrolling appears to be inverted for me in the current examples. This is potentially complicated by the fact that I am using macOS with "natural scrolling" enabled (so drag down on touchpad to scroll up and vice versa). But I believe this should be transparent to the application (and even Winit).

**Comment by Philipp-M** [comment]
Just tagging this: https://github.com/linebender/xilem/pull/182 as there was more discussion on this already.

**Comment by jaredoconnell** [comment]
To add more data, I'm on Mac OS with natural scrolling disabled, and it's also backwards for me.

**Comment by DJMcNab** [comment]
I'm on a Fedora Wayland system, and I also see this. It looks like whatever was causing it to need to be the other way only applies to @xorgy's system. In #182, it was suggested to try iced - Aaron, can you do that and see whether their examples scroll as you would expect?

**Comment by xorgy** [comment]
I think it's just that I tested on Weston, and it has unnatural scrolling by default for some reason. I'd be happy to merge the reversal.

**Comment by xorgy** [comment]
Up until this point, there is no transformation of the event, so it's just a matter of swapping `y` for `-y` on this line, which makes sense since that's what has to be done with the Line scrolling as well.
https://github.com/linebender/xilem/commit/a13a814e35ad0abc81f8146f26ed73cc662e9814#diff-c0bc115777c47751aa5808ee73345d59943fb4062a5da09bb1d28c30f01e3062R93

**Comment by lokxii** [comment]
Hope this can be merged upon more testing on more platforms as a temporary fix
