### ISSUE TITLE
Scale issue on iOS

### ISSUE THREAD

**Issue by johanholmerin** [linebender/xilem#419]
I'm experiencing some rendering issues when running xilem on iOS. The content is stretched vertically compared to how it looks on android and macOS. The touch targets also differ from how the content is rendered so you have to tap above the buttons for them to work.

Repo: https://github.com/johanholmerin/xilem-cross-platform

<details>
  <summary>iOS</summary>

![xilem ios](https://github.com/linebender/xilem/assets/7433263/8bde0880-90e7-498b-b45c-c9964a0ae153)

</details>

<details>
  <summary>android</summary>

![xilem android](https://github.com/linebender/xilem/assets/7433263/74f3508d-98f2-418d-b73f-550f1d68f15e)

</details>

**Comment by DJMcNab** [comment]
I believe that this issue is https://github.com/rust-windowing/winit/issues/2308

I don't think we can do very much here - winit doesn't expose the correct APIs at the moment. If you can apply a targeted hack, I think we would probably land it, but we do not support iOS on anything other than a best-effort basis.
