### ISSUE TITLE
Masonry unit tests fail in release mode

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/xilem#477]
Some tests specifically check that some checks run, but those checks only run when `debug_assertions` is true.

This means those tests fail when running `cargo test --release`.

The tests should be cfg-ed out or otherwise changed.

**Comment by PoignardAzur** [comment]
Fixed by #233.

**Comment by DJMcNab** [comment]
I'm not convinced that PR "fixed" it; it only masked the issue by ignoring the relevant tests.

Practically, however, I don't think any actions needs to be taken here, since CI runs the tests with `debug_assertions` enabled. So I think this is fine to be closed, but I'm going to close it as not planned.

**Comment by PoignardAzur** [comment]
I don't think there's a problem. The behavior being tested was "masonry panics when some bad things happen in dev mode". It makes sense to only run the tests in dev mode.
