### ISSUE TITLE
Run doctests in CI

### ISSUE THREAD

**Issue by DJMcNab** [linebender/xilem#500]
Since #233 moved to using `cargo nextest`, we no longer run doc tests. This is because of https://github.com/nextest-rs/nextest/issues/16

We should apply the workaround discussed in https://github.com/nextest-rs/nextest/issues/16, of adding a separate step to run doctests.
This will likely require remedial work to resolve any compilation issues which are present in our tests.

This issue also applies to [Vello](https://github.com/linebender/vello/).

**Comment by matta** [comment]
I've sent a PR but I'm confused about @DJMcNab's comment:

> This issue also applies to [Vello](https://github.com/linebender/vello/).

..because https://github.com/linebender/vello/commit/91c945a007e5df30ce374ffe8656929c6daa1d94 seems to have set up doctests correctly and they're still running in vello CI.

It does raise the question: should xilem follow suit and run doc tests on just a single platform? Currently they run quickly so I'm not sure the how to weigh the compute cost vs. potential for bit rot if nobody notices that a platform specific doctest manifests.

**Comment by DJMcNab** [comment]
I don't think that PR touched doc tests. The commit message is wrong.

That PR checks that the *documentation* builds correctly, but it isn't actually running the doc tests. Indeed, in that PR the `cargo test` runs are what are running the doc tests.
