### ISSUE TITLE
White flash on app startup on Windows 11 dark mode

### ISSUE THREAD

**Issue by gfxenjoyer** [linebender/xilem#590]
Xilem apps have a white flash on Windows even on dark mode. This does not happen on macOS. I suspect this has something to do with winit.

Hardware:
OS: Windows 11 23H2 OS Build 22631.4169
CPU: Intel 12600k
GPU: Nvidia RTX 3080 Driver 560.70

This also happens in [Vello examples](https://github.com/linebender/vello/tree/main/examples/with_winit).

Reference [Zulipchat](https://xi.zulipchat.com/#narrow/stream/354396-xilem/topic/Startup.20white.20background.20flash.20on.20Windows.20dark.20mode)

[xilem_calc_white_flash_windows.webm](https://github.com/user-attachments/assets/5af55497-c882-41ef-acfc-6dfc7263204f)

Edit: 
Calc build in video shown is a release build.

**Comment by DJMcNab** [comment]
Thanks for the report. I believe that there are a few things going on here:
- Windows will set a fully white buffer as the window contents initially. I don't know where this behaviour is documented
- Graphics initialisation is taking a while on your machine. This doesn't really make sense, because your GPU is quite powerful; the biggest issue should have been resolved in linebender/vello#575
- We might not `present` "soon enough" after making the window visible - see https://github.com/linebender/xilem/blob/b54266d605b597d967e4b13dcf04d2e43ce43691/masonry/src/event_loop_runner.rs#L261, but GPU initialisation hasn't happened yet.

Ultimately, I can't afford the time to dig into this at the moment, but hopefully this gives you some good directions to look towards when investigating this. In particular, you should try and find some documentation expressing a correct startup sequence for an app on Windows, or else perform some experiments (such as only making the window visible immediately before we call `present` for the first time - I am slightly concerned that rendering wouldn't be scheduled in that case...)

**Comment by DJMcNab** [comment]
A pr which experimentally implements that would be welcome!
